from sqlalchemy import (Column, String, Date, Float, Boolean, BigInteger,
                        create_engine, UniqueConstraint)
from sqlalchemy.ext.declarative import declarative_base

def connect(user, password, db, host='localhost', port=5432):
    '''Returns a connection and a metadata object'''
    # We connect with the help of the PostgreSQL URL
    url = 'postgresql://{}:{}@{}:{}/{}'
    url = url.format(user, password, host, port, db)

    con = create_engine(url, client_encoding='utf8')
    return con

Base = declarative_base()

class YahooKeyStatistics(Base):
    __tablename__ = 'key_statistics'
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    ticker = Column(String, autoincrement=False, nullable=False, primary_key=True)
    update_date = Column(Date, autoincrement=False, nullable=False)
    forward_pe = Column(Float, autoincrement=False, nullable=True)
    ro_equity = Column(Float, autoincrement=False, nullable=True)
    current_ratio = Column(Float, autoincrement=False, nullable=True)
    total_debt = Column(BigInteger, autoincrement=False, nullable=True)
    forward_annual_dividend_rate = Column(Float, autoincrement=False, nullable=True)
    market_cap = Column(BigInteger, autoincrement=False, nullable=True)
    ebitda = Column(BigInteger, autoincrement=False, nullable=True)
    shares_short = Column(BigInteger, autoincrement=False, nullable=True)
    fifty_day_moving_avg = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_high = Column(Float, autoincrement=False, nullable=True)
    q_earnings_growth = Column(Float, autoincrement=False, nullable=True)
    forward_annual_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    beta = Column(Float, autoincrement=False, nullable=True)
    payout_ratio = Column(Float, autoincrement=False, nullable=True)
    avg_vol_3_month = Column(BigInteger, autoincrement=False, nullable=True)
    enterprise_value = Column(BigInteger, autoincrement=False, nullable=True)
    five_year_avg_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    enterprise_value_revenue = Column(Float, autoincrement=False, nullable=True)
    trailing_pe = Column(Float, autoincrement=False, nullable=True)
    total_cash = Column(BigInteger, autoincrement=False, nullable=True)
    operating_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    price_book = Column(Float, autoincrement=False, nullable=True)
    total_debt_equity = Column(Float, autoincrement=False, nullable=True)
    profit_margin = Column(Float, autoincrement=False, nullable=True)
    operating_margin = Column(Float, autoincrement=False, nullable=True)
    perc_held_by_institutions = Column(Float, autoincrement=False, nullable=True)
    trailing_annual_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    two_hundred_day_moving_avg = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_low = Column(Float, autoincrement=False, nullable=True)
    last_split_factor = Column(String, autoincrement=False, nullable=True)
    avg_vol_10_day = Column(BigInteger, autoincrement=False, nullable=True)
    perc_held_by_insiders = Column(Float, autoincrement=False, nullable=True)
    revenue_per_share = Column(Float, autoincrement=False, nullable=True)
    short_ratio = Column(Float, autoincrement=False, nullable=True)
    shares_short_prior_month = Column(BigInteger, autoincrement=False, nullable=True)
    short_perc_float = Column(Float, autoincrement=False, nullable=True)
    ro_assets = Column(Float, autoincrement=False, nullable=True)
    price_sales = Column(Float, autoincrement=False, nullable=True)
    gross_profit = Column(BigInteger, autoincrement=False, nullable=True)
    book_value_per_share = Column(Float, autoincrement=False, nullable=True)
    levered_free_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    trailing_annual_dividend_rate = Column(Float, autoincrement=False, nullable=True)
    diluted_eps = Column(Float, autoincrement=False, nullable=True)
    peg_ratio_5yr = Column(Float, autoincrement=False, nullable=True)
    shares_outstanding = Column(BigInteger, autoincrement=False, nullable=True)
    revenue = Column(BigInteger, autoincrement=False, nullable=True)
    float = Column(BigInteger, autoincrement=False, nullable=True)
    net_income_avi_common = Column(BigInteger, autoincrement=False, nullable=True)
    enterprise_value_ebitda = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_change = Column(Float, autoincrement=False, nullable=True)
    q_revenue_growth = Column(Float, autoincrement=False, nullable=True)
    total_cash_ps = Column(Float, autoincrement=False, nullable=True)
    fiscal_year_ends = Column(Date, autoincrement=False, nullable=True)
    most_recent_q = Column(Date, autoincrement=False, nullable=True)
    dividend_date = Column(Date, autoincrement=False, nullable=True)
    last_split_date = Column(Date, autoincrement=False, nullable=True)
    exdividend_date = Column(Date, autoincrement=False, nullable=True)
