from sqlalchemy import (Column, String, Date, Float, Boolean, BigInteger,
                        create_engine, UniqueConstraint)
from sqlalchemy.ext.declarative import declarative_base

def connect(user, password, db, host='localhost', port=5432):
    '''Returns a connection and a metadata object'''
    # We connect with the help of the PostgreSQL URL
    url = 'postgresql://{}:{}@{}:{}/{}'
    url = url.format(user, password, host, port, db)

    con = create_engine(url, client_encoding='utf8')
    return con

Base = declarative_base()

class Listings(Base):
    __tablename__ = 'listings'
    ticker = Column(String, autoincrement=False, nullable=True, primary_key=True)
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    sector = Column(String, autoincrement=False, nullable=True)
    osshares = Column(BigInteger, autoincrement=False, nullable=True)
    name = Column(String, autoincrement=False, nullable=True)
    dateoflisting = Column(Date, autoincrement=False, nullable=True)
    listingtype = Column(String, autoincrement=False, nullable=True)
    value = Column(BigInteger, autoincrement=False, nullable=True)
    updatedate = Column(Date, autoincrement=False, nullable=True)
    volume = Column(BigInteger, autoincrement=False, nullable=True)
    onyahoo = Column(Boolean, autoincrement=False, nullable=True)
    onms = Column(Boolean, autoincrement=False, nullable=True)

class EventHistory(Base):
    __tablename__ = 'event_history'
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    ticker = Column(String, autoincrement=False, nullable=True, primary_key=True)
    date = Column(Date, autoincrement=False, nullable=True, primary_key=True)
    action = Column(String, autoincrement=False, nullable=True)
    value = Column(Float, autoincrement=False, nullable=True)
    updatedate = Column(Date, autoincrement=False, nullable=True)

class PriceHistory(Base):
    __tablename__ = 'price_history'
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    ticker = Column(String, autoincrement=False, nullable=True, primary_key=True)
    date = Column(Date, autoincrement=False, nullable=True, primary_key=True)
    low = Column(Float, autoincrement=False, nullable=True)
    high = Column(Float, autoincrement=False, nullable=True)
    open = Column(Float, autoincrement=False, nullable=True)
    close = Column(Float, autoincrement=False, nullable=True)
    adj_close = Column(Float, autoincrement=False, nullable=True)
    volume = Column(BigInteger, autoincrement=False, nullable=True)

class MorningStarFinancials(Base):
    __tablename__ = 'ms_financials'
    ticker = Column(String, autoincrement=False, nullable=True, primary_key=True)
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    update_date = Column(Date, autoincrement=False, nullable=True)
    revenue = Column(BigInteger, autoincrement=False, nullable=True)
    revenue_cost = Column(BigInteger, autoincrement=False, nullable=True)
    gross_profit = Column(BigInteger, autoincrement=False, nullable=True)
    sales_expense = Column(BigInteger, autoincrement=False, nullable=True)
    operating_expense = Column(BigInteger, autoincrement=False, nullable=True)
    other_income = Column(BigInteger, autoincrement=False, nullable=True)
    other_expense = Column(BigInteger, autoincrement=False, nullable=True)
    other_assets = Column(BigInteger, autoincrement=False, nullable=True)
    other = Column(BigInteger, autoincrement=False, nullable=True)
    operating_income = Column(BigInteger, autoincrement=False, nullable=True)
    intrest_expense = Column(BigInteger, autoincrement=False, nullable=True)
    total_costs = Column(BigInteger, autoincrement=False, nullable=True)
    preferred_dividend = Column(BigInteger, autoincrement=False, nullable=True)
    income_before_taxes = Column(BigInteger, autoincrement=False, nullable=True)
    provision_taxes = Column(BigInteger, autoincrement=False, nullable=True)
    net_income_continuing_ops = Column(BigInteger, autoincrement=False, nullable=True)
    net_income_common = Column(BigInteger, autoincrement=False, nullable=True)
    net_income = Column(BigInteger, autoincrement=False, nullable=True)
    eps_basic = Column(Float, autoincrement=False, nullable=True)
    eps_diluted = Column(Float, autoincrement=False, nullable=True)
    waso_basic = Column(BigInteger, autoincrement=False, nullable=True)
    waso_diluted = Column(BigInteger, autoincrement=False, nullable=True)
    ebitda = Column(BigInteger, autoincrement=False, nullable=True)
    fiscal_year = Column(Date, autoincrement=False, nullable=True)
    period = Column(String, autoincrement=False, nullable=True)
    net_income_discontinuing_ops = Column(BigInteger, autoincrement=False, nullable=True)
    UniqueConstraint('ticker', 'exchange', 'fiscal_year', 'period', 'fiscal_year_unique')

class YahooKeyStatistics(Base):
    __tablename__ = 'yahoo_key_statistics'
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    ticker = Column(String, autoincrement=False, nullable=False, primary_key=True)
    update_date = Column(Date, autoincrement=False, nullable=False, primary_key=True)
    name = Column(String, autoincrement=False, nullable=True)
    pe = Column(Float, autoincrement=False, nullable=True)
    dividend_yield = Column(Float, autoincrement=False, nullable=True)
    dividend_ps = Column(Float, autoincrement=False, nullable=True)
    dividend_pay_date = Column(Date, autoincrement=False, nullable=True)
    ex_dividend_date = Column(Date, autoincrement=False, nullable=True)
    open = Column(Float, autoincrement=False, nullable=True)
    change = Column(Float, autoincrement=False, nullable=True)
    perc_change = Column(Float, autoincrement=False, nullable=True)
    last_trade_date = Column(Date, autoincrement=False, nullable=True)
    trade_date = Column(Date, autoincrement=False, nullable=True)
    commission = Column(Float, autoincrement=False, nullable=True)
    day_low = Column(Float, autoincrement=False, nullable=True)
    day_high = Column(Float, autoincrement=False, nullable=True)
    previous_close = Column(Float, autoincrement=False, nullable=True)
    year_target = Column(Float, autoincrement=False, nullable=True)
    change_mv_avg_200 = Column(Float, autoincrement=False, nullable=True)
    perc_change_mv_avg_200 = Column(Float, autoincrement=False, nullable=True)
    change_mv_avg_50 = Column(Float, autoincrement=False, nullable=True)
    perc_change_mv_avg_50 = Column(Float, autoincrement=False, nullable=True)
    mv_avg_50 = Column(Float, autoincrement=False, nullable=True)
    mv_avg_200 = Column(Float, autoincrement=False, nullable=True)
    day_value_change = Column(Float, autoincrement=False, nullable=True)
    holding_gain_perc = Column(Float, autoincrement=False, nullable=True)
    annualized_gain = Column(Float, autoincrement=False, nullable=True)
    holdings_gain = Column(Float, autoincrement=False, nullable=True)
    high_52_week = Column(Float, autoincrement=False, nullable=True)
    low_52_week = Column(Float, autoincrement=False, nullable=True)
    change_52_week_low = Column(Float, autoincrement=False, nullable=True)
    change_52_week_high = Column(Float, autoincrement=False, nullable=True)
    perc_change_52_week_low = Column(Float, autoincrement=False, nullable=True)
    perc_change_52_week_high = Column(Float, autoincrement=False, nullable=True)
    market_cap = Column(BigInteger, autoincrement=False, nullable=True)
    float_shares = Column(BigInteger, autoincrement=False, nullable=True)
    stock_exchange = Column(String, autoincrement=False, nullable=True)
    shares_owned = Column(BigInteger, autoincrement=False, nullable=True)
    shares_outstanding = Column(BigInteger, autoincrement=False, nullable=True)
    notes = Column(String, autoincrement=False, nullable=True)
    more_info = Column(String, autoincrement=False, nullable=True)
    ask = Column(Float, autoincrement=False, nullable=True)
    bid = Column(Float, autoincrement=False, nullable=True)
    volume = Column(BigInteger, autoincrement=False, nullable=True)
    avg_daily_volume = Column(BigInteger, autoincrement=False, nullable=True)
    eps = Column(Float, autoincrement=False, nullable=True)
    eps_year_estimate = Column(Float, autoincrement=False, nullable=True)
    eps_next_year_estimate = Column(Float, autoincrement=False, nullable=True)
    eps_next_q_estimate = Column(Float, autoincrement=False, nullable=True)
    book = Column(Float, autoincrement=False, nullable=True)
    ebitda = Column(Float, autoincrement=False, nullable=True)
    price_sale = Column(Float, autoincrement=False, nullable=True)
    price_book = Column(Float, autoincrement=False, nullable=True)
    pe = Column(Float, autoincrement=False, nullable=True)
    peg = Column(Float, autoincrement=False, nullable=True)
    price_eps_estimate_year = Column(Float, autoincrement=False, nullable=True)
    price_eps_estimate_next_year = Column(Float, autoincrement=False, nullable=True)
    short_ratio = Column(Float, autoincrement=False, nullable=True)
    revenue = Column(BigInteger, autoincrement=False, nullable=True)
    holdings_val = Column(BigInteger, autoincrement=False, nullable=True)
    high_limit = Column(Float, autoincrement=False, nullable=True)
    low_limit = Column(Float, autoincrement=False, nullable=True)

class MorningStarKeyStatistics(Base):
    __tablename__ = 'ms_key_statistics'
    ticker = Column(String, autoincrement=False, nullable=True, primary_key=True)
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    update_date = Column(Date, autoincrement=False, nullable=True)
    revenue = Column(BigInteger, autoincrement=False, nullable=True)
    gross_margin = Column(Float, autoincrement=False, nullable=True)
    operating_income = Column(BigInteger, autoincrement=False, nullable=True)
    operating_margin = Column(Float, autoincrement=False, nullable=True)
    net_income = Column(BigInteger, autoincrement=False, nullable=True)
    eps = Column(Float, autoincrement=False, nullable=True)
    dividends = Column(Float, autoincrement=False, nullable=True)
    payout_ratio = Column(Float, autoincrement=False, nullable=True)
    num_shares = Column(BigInteger, autoincrement=False, nullable=True)
    book_value_ps = Column(Float, autoincrement=False, nullable=True)
    operating_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    cap_spending = Column(BigInteger, autoincrement=False, nullable=True)
    free_cash_flow_ps = Column(Float, autoincrement=False, nullable=True)
    free_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    working_captial = Column(BigInteger, autoincrement=False, nullable=True)
    revenue_per_sales = Column(Float, autoincrement=False, nullable=True)
    revenue_per_cogs = Column(Float, autoincrement=False, nullable=True)
    sales_gross_margin = Column(Float, autoincrement=False, nullable=True)
    margin_sga = Column(Float, autoincrement=False, nullable=True)
    margin_rd = Column(Float, autoincrement=False, nullable=True)
    margin_other = Column(Float, autoincrement=False, nullable=True)
    margin_operating = Column(Float, autoincrement=False, nullable=True)
    margin_net_income = Column(Float, autoincrement=False, nullable=True)
    margin_ebt = Column(Float, autoincrement=False, nullable=True)
    tax_rate = Column(Float, autoincrement=False, nullable=True)
    net_margin_perc = Column(Float, autoincrement=False, nullable=True)
    asset_turnover = Column(Float, autoincrement=False, nullable=True)
    ro_assets = Column(Float, autoincrement=False, nullable=True)
    financial_leverage = Column(Float, autoincrement=False, nullable=True)
    ro_equity = Column(Float, autoincrement=False, nullable=True)
    ro_invested_captial = Column(Float, autoincrement=False, nullable=True)
    interest_coverage = Column(Float, autoincrement=False, nullable=True)
    revenue_perc_yoy = Column(Float, autoincrement=False, nullable=True)
    revenue_perc_3y = Column(Float, autoincrement=False, nullable=True)
    revenue_perc_5y = Column(Float, autoincrement=False, nullable=True)
    revenue_perc_10y = Column(Float, autoincrement=False, nullable=True)
    operating_income_yoy = Column(Float, autoincrement=False, nullable=True)
    operating_income_3y = Column(Float, autoincrement=False, nullable=True)
    operating_income_5y = Column(Float, autoincrement=False, nullable=True)
    operating_income_10y = Column(Float, autoincrement=False, nullable=True)
    net_income_yoy = Column(Float, autoincrement=False, nullable=True)
    net_income_3y = Column(Float, autoincrement=False, nullable=True)
    net_income_5y = Column(Float, autoincrement=False, nullable=True)
    net_income_10y = Column(Float, autoincrement=False, nullable=True)
    eps_yoy = Column(Float, autoincrement=False, nullable=True)
    eps_3y = Column(Float, autoincrement=False, nullable=True)
    eps_5y = Column(Float, autoincrement=False, nullable=True)
    eps_10y = Column(Float, autoincrement=False, nullable=True)
    cash_flow_operating_growth_yoy = Column(Float, autoincrement=False, nullable=True)
    free_cash_flow_growth_yoy = Column(Float, autoincrement=False, nullable=True)
    cap_expense_perc_sales = Column(Float, autoincrement=False, nullable=True)
    free_cash_flow_sales = Column(Float, autoincrement=False, nullable=True)
    free_cash_flow_net_income = Column(Float, autoincrement=False, nullable=True)
    cash_short_term = Column(Float, autoincrement=False, nullable=True)
    accounts_receivable = Column(Float, autoincrement=False, nullable=True)
    inventory = Column(Float, autoincrement=False, nullable=True)
    other_cur_assets = Column(Float, autoincrement=False, nullable=True)
    total_cur_assets = Column(Float, autoincrement=False, nullable=True)
    net_ppe = Column(Float, autoincrement=False, nullable=True)
    intangibles = Column(Float, autoincrement=False, nullable=True)
    other_long_term_assets = Column(Float, autoincrement=False, nullable=True)
    accounts_payable = Column(Float, autoincrement=False, nullable=True)
    short_term_debt = Column(Float, autoincrement=False, nullable=True)
    taxes_payable = Column(Float, autoincrement=False, nullable=True)
    accured_liabilities = Column(Float, autoincrement=False, nullable=True)
    short_term_liabilities = Column(Float, autoincrement=False, nullable=True)
    long_term_debt = Column(Float, autoincrement=False, nullable=True)
    total_liabilities = Column(Float, autoincrement=False, nullable=True)
    total_stockholder = Column(Float, autoincrement=False, nullable=True)
    current_ratio = Column(Float, autoincrement=False, nullable=True)
    quick_ratio = Column(Float, autoincrement=False, nullable=True)
    debt_equity = Column(Float, autoincrement=False, nullable=True)
    receivables_turnover = Column(Float, autoincrement=False, nullable=True)
    inventory_turnover = Column(Float, autoincrement=False, nullable=True)
    fixed_assets_turnover = Column(Float, autoincrement=False, nullable=True)
    margin_date = Column(Date, autoincrement=False, nullable=True, primary_key=True)
    profitability_date = Column(Date, autoincrement=False, nullable=True)
    total_liabilities_equity = Column(Float, autoincrement=False, nullable=True)

class KeyStatistics(Base):
    __tablename__ = 'key_statistics'
    exchange = Column(String, autoincrement=False, nullable=True, primary_key=True)
    ticker = Column(String, autoincrement=False, nullable=False, primary_key=True)
    update_date = Column(Date, autoincrement=False, nullable=False)
    forward_pe = Column(Float, autoincrement=False, nullable=True)
    ro_equity = Column(Float, autoincrement=False, nullable=True)
    current_ratio = Column(Float, autoincrement=False, nullable=True)
    total_debt = Column(BigInteger, autoincrement=False, nullable=True)
    forward_annual_dividend_rate = Column(Float, autoincrement=False, nullable=True)
    market_cap = Column(BigInteger, autoincrement=False, nullable=True)
    ebitda = Column(BigInteger, autoincrement=False, nullable=True)
    shares_short = Column(BigInteger, autoincrement=False, nullable=True)
    fifty_day_moving_avg = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_high = Column(Float, autoincrement=False, nullable=True)
    q_earnings_growth = Column(Float, autoincrement=False, nullable=True)
    forward_annual_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    beta = Column(Float, autoincrement=False, nullable=True)
    payout_ratio = Column(Float, autoincrement=False, nullable=True)
    avg_vol_3_month = Column(BigInteger, autoincrement=False, nullable=True)
    enterprise_value = Column(BigInteger, autoincrement=False, nullable=True)
    five_year_avg_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    enterprise_value_revenue = Column(Float, autoincrement=False, nullable=True)
    trailing_pe = Column(Float, autoincrement=False, nullable=True)
    total_cash = Column(BigInteger, autoincrement=False, nullable=True)
    operating_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    price_book = Column(Float, autoincrement=False, nullable=True)
    total_debt_equity = Column(Float, autoincrement=False, nullable=True)
    profit_margin = Column(Float, autoincrement=False, nullable=True)
    operating_margin = Column(Float, autoincrement=False, nullable=True)
    perc_held_by_institutions = Column(Float, autoincrement=False, nullable=True)
    trailing_annual_dividend_yield = Column(Float, autoincrement=False, nullable=True)
    two_hundred_day_moving_avg = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_low = Column(Float, autoincrement=False, nullable=True)
    last_split_factor = Column(String, autoincrement=False, nullable=True)
    avg_vol_10_day = Column(BigInteger, autoincrement=False, nullable=True)
    perc_held_by_insiders = Column(Float, autoincrement=False, nullable=True)
    revenue_per_share = Column(Float, autoincrement=False, nullable=True)
    short_ratio = Column(Float, autoincrement=False, nullable=True)
    shares_short_prior_month = Column(BigInteger, autoincrement=False, nullable=True)
    short_perc_float = Column(Float, autoincrement=False, nullable=True)
    ro_assets = Column(Float, autoincrement=False, nullable=True)
    price_sales = Column(Float, autoincrement=False, nullable=True)
    gross_profit = Column(BigInteger, autoincrement=False, nullable=True)
    book_value_per_share = Column(Float, autoincrement=False, nullable=True)
    levered_free_cash_flow = Column(BigInteger, autoincrement=False, nullable=True)
    trailing_annual_dividend_rate = Column(Float, autoincrement=False, nullable=True)
    diluted_eps = Column(Float, autoincrement=False, nullable=True)
    peg_ratio_5yr = Column(Float, autoincrement=False, nullable=True)
    shares_outstanding = Column(BigInteger, autoincrement=False, nullable=True)
    revenue = Column(BigInteger, autoincrement=False, nullable=True)
    float = Column(BigInteger, autoincrement=False, nullable=True)
    net_income_avi_common = Column(BigInteger, autoincrement=False, nullable=True)
    enterprise_value_ebitda = Column(Float, autoincrement=False, nullable=True)
    fifty_two_week_change = Column(Float, autoincrement=False, nullable=True)
    q_revenue_growth = Column(Float, autoincrement=False, nullable=True)
    total_cash_ps = Column(Float, autoincrement=False, nullable=True)
    fiscal_year_ends = Column(Date, autoincrement=False, nullable=True)
    most_recent_q = Column(Date, autoincrement=False, nullable=True)
    dividend_date = Column(Date, autoincrement=False, nullable=True)
    last_split_date = Column(Date, autoincrement=False, nullable=True)
    exdividend_date = Column(Date, autoincrement=False, nullable=True)

if __name__ == '__main__':
    from sa.database import engine
    Base.metadata.create_all(engine)
